### PR TITLE
Ingo merge ingokarkat fork

### PR DESCRIPTION
**Pull request by idbrii**
I merged a ton of changes from @inkarkat's renamer.vim repo. I haven't done a lot of testing, but wanted to get some feedback on the change.

I couldn't merge these changes because I think they were implemented (in a different way) in fc95e9a8b256ae128b1b7279b0cc8024ebf93f3f:
- inkarkat/renamer.vim@0d9cb0d  ENH: Allow recursive file listing. (2 years, 4 months ago)
- inkarkat/renamer.vim@13afe2d  Fix validChars for multi-byte file name (4 years, 1 month ago)

It contains some vimscript cleanup/refactoring, improved tooltips, and a test rename command.

### CODE REVIEW

**Comment by idbrii** [comment]
My process for getting these changes:
- Rebase inkarkat's tree onto 033adeca81579aff1e009ef5bc9a8a390a2c23bc which matches inkarkat/renamer.vim@063283fb4ea933d53659cf6764156086847ab174. This change that's common to both repos but since I foolishly updated my name in commits the hash is different.
- Cherry-pick changes from the rebased tree onto 2.1 (so I could tell what applied cleanly).
- Rebase new tree onto master.

I did some merging but bailed when it got hairy. Usually it was pretty simple since inkarkat's changes are mostly atomic.

**Comment by qpkorr** [comment]
Thank you - sorry it took me a while to get to these!  I've not tested them yet, but looked at the changes and they look good.  I'll do some testing soon and in the unlikely event I find problems, I'll try to fix them.

**Comment by qpkorr** [comment]
Found one bug from the merge, will upload what I think is the simple fix.

**Comment by qpkorr** [comment]
Gah. Can't push my fixes as I'm behind github, but pulling from github says I'm up to date.  Sometimes git's debug info is most unhelpful...

**Comment by idbrii** [comment]
You could try using the graph to see where your branches are in the overall
timeline: http://stackoverflow.com/a/9074343/79125
It's possible git's fetched all the commits, but they're not merged in
locally.

As a blind guess, `git merge origin/master` might also do it.

-David

**Comment by qpkorr** [comment]
Thank you - the complicating factor was I was using git subtrees - I don't have time to dig into the details but I hope I've fixed it thanks to this post http://stackoverflow.com/questions/13756055/git-subtree-subtree-up-to-date-but-cant-push  (though I'm always nervous when "--force" is involved!)  I'll try to do some more testing and see if anything pops up - and then potentially get onto his other two changes.  Thanks again!

**Pull request merged**
